name: FroxyCore
main: com.froxynetwork.froxycore.FroxyCore
version: 0.1.4
author: 0ddlyoko
commands:
  box:
    description: help box
permissions:
  box.give:
    default: op
    description: Ajouter des clés à des joueurs